version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb/
    networks:
      - mynetwork
    restart: on-failure
  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - "443:443"
    networks:
      - mynetwork
    restart: on-failure
networks:
  mynetwork:
